#!/bin/sh
#
# A hook script to check the commit log message taken by
# applypatch from an e-mail message (via git-am).
# We simply do the same as for other commit messages
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.  The hook is
# allowed to edit the commit message file.
#

. git-sh-setup
test -x "$GIT_DIR/hooks/commit-msg" &&
	exec "$GIT_DIR/hooks/commit-msg" ${1+"$@"}
:
