on:
  push:
    tags:
      - 'v*.*.*'

name: release

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential meson ninja-build pkg-config python3-sphinx libcmocka-dev libpci-dev libusb-1.0-0-dev libftdi1-dev 
